[tool.poetry]
name = "issue_1757"
version = "0.1.0"
description = ""
authors = ["Example <finswimmer@example.org>"]

[tool.poetry.dependencies]
python = "^3.8"
packageA = {path = "./packagea"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
