[tool.poetry]
name = "packageb"
version = "0.1.0"
description = ""
authors = ["Example <finswimmer@example.org>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
